<?php

use Illuminate\Database\Seeder;
use App\Surat;

class SuratSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Surat::insert([
            ['surat_id'=> 'Surah Al-Fatihah','ayat'=>'7',],
            ['surat_id'=> 'Surah Al-Baqarah','ayat'=>'286',],
            ['surat_id'=> 'Surah Ali `Imran','ayat'=>'200',],
            ['surat_id'=> 'Surah An-Nisa`','ayat'=>'176',],
            ['surat_id'=> 'Surah Al-Ma`idah','ayat'=>'120',],
            ['surat_id'=> 'Surah Al-An`am','ayat'=>'165',],
            ['surat_id'=> 'Surah Al-A`raf','ayat'=>'206',],
            ['surat_id'=> 'Surah Al-Anfal','ayat'=>'75',],
            ['surat_id'=> 'Surah At-Taubah','ayat'=>'129',],
            ['surat_id'=> 'Surah Yunus','ayat'=>'109',],
            ['surat_id'=> 'Surah Hud','ayat'=>'123',],
            ['surat_id'=> 'Surah Yusuf','ayat'=>'111',],
            ['surat_id'=> 'Surah Ar-Ra`d','ayat'=>'43',],
            ['surat_id'=> 'Surah Ibrahim','ayat'=>'52',],
            ['surat_id'=> 'Surah Al-Hijr','ayat'=>'99',],
            ['surat_id'=> 'Surah An-Nahl','ayat'=>'128',],
            ['surat_id'=> 'Surah Al-Isra`','ayat'=>'111',],
            ['surat_id'=> 'Surah Al-Kahf','ayat'=>'110',],
            ['surat_id'=> 'Surah Maryam','ayat'=>'98',],
            ['surat_id'=> 'Surah Ta Ha','ayat'=>'135',],
            ['surat_id'=> 'Surah Al-Anbiya','ayat'=>'112',],
            ['surat_id'=> 'Surah Al-Hajj','ayat'=>'78',],
            ['surat_id'=> 'Surah Al-Mu`minun','ayat'=>'118',],
            ['surat_id'=> 'Surah An-Nur','ayat'=>'64',],
            ['surat_id'=> 'Surah Al-Furqan','ayat'=>'77',],
            ['surat_id'=> 'Surah Asy-Syu`ara`','ayat'=>'227',],
            ['surat_id'=> 'Surah An-Naml','ayat'=>'93',],
            ['surat_id'=> 'Surah Al-Qasas','ayat'=>'88',],
            ['surat_id'=> 'Surah Al-`Ankabut','ayat'=>'69',],
            ['surat_id'=> 'Surah Ar-Rum','ayat'=>'60',],
            ['surat_id'=> 'Surah Luqman','ayat'=>'34',],
            ['surat_id'=> 'Surah As-Sajdah','ayat'=>'30',],
            ['surat_id'=> 'Surah Al-Ahzab','ayat'=>'73',],
            ['surat_id'=> 'Surah Saba`','ayat'=>'54',],
            ['surat_id'=> 'Surah Fatir','ayat'=>'45',],
            ['surat_id'=> 'Surah Ya Sin','ayat'=>'83',],
            ['surat_id'=> 'Surah As-Saffat','ayat'=>'182',],
            ['surat_id'=> 'Surah Sad','ayat'=>'88',],
            ['surat_id'=> 'Surah Az-Zumar','ayat'=>'75',],
            ['surat_id'=> 'Surah Al-Mu`min','ayat'=>'85',],
            ['surat_id'=> 'Surah Fussilat','ayat'=>'54',],
            ['surat_id'=> 'Surah Asy-Syura','ayat'=>'53',],
            ['surat_id'=> 'Surah Az-Zukhruf','ayat'=>'89',],
            ['surat_id'=> 'Surah Ad-Dukhan','ayat'=>'59',],
            ['surat_id'=> 'Surah Al-Jasiyah','ayat'=>'37',],
            ['surat_id'=> 'Surah Al-Ahqaf','ayat'=>'35',],
            ['surat_id'=> 'Surah Muhammad','ayat'=>'38',],
            ['surat_id'=> 'Surah Al-Fath','ayat'=>'29',],
            ['surat_id'=> 'Surah Al-Hujurat','ayat'=>'18',],
            ['surat_id'=> 'Surah Qaf','ayat'=>'45',],
            ['surat_id'=> 'Surah Az-Zariyat','ayat'=>'60',],
            ['surat_id'=> 'Surah At-Tur','ayat'=>'49',],
            ['surat_id'=> 'Surah An-Najm','ayat'=>'62',],
            ['surat_id'=> 'Surah Al-Qamar','ayat'=>'55',],
            ['surat_id'=> 'Surah Ar-Rahman','ayat'=>'78',],
            ['surat_id'=> 'Surah Al-Waqi`ah','ayat'=>'96',],
            ['surat_id'=> 'Surah Al-Hadid','ayat'=>'29',],
            ['surat_id'=> 'Surah Al-Mujadilah','ayat'=>'22',],
            ['surat_id'=> 'Surah Al-Hasyr','ayat'=>'24',],
            ['surat_id'=> 'Surah Al-Mumtahanah','ayat'=>'13',],
            ['surat_id'=> 'Surah As-Saff','ayat'=>'14',],
            ['surat_id'=> 'Surah Al-Jumu`ah','ayat'=>'11',],
            ['surat_id'=> 'Surah Al-Munafiqun','ayat'=>'11',],
            ['surat_id'=> 'Surah At-Tagabun','ayat'=>'18',],
            ['surat_id'=> 'Surah At-Talaq','ayat'=>'12',],
            ['surat_id'=> 'Surah At-Tahrim','ayat'=>'12',],
            ['surat_id'=> 'Surah Al-Mulk','ayat'=>'30',],
            ['surat_id'=> 'Surah Al-Qalam','ayat'=>'52',],
            ['surat_id'=> 'Surah Al-Haqqah','ayat'=>'52',],
            ['surat_id'=> 'Surah Al-Ma`arij','ayat'=>'44',],
            ['surat_id'=> 'Surah Nuh','ayat'=>'28',],
            ['surat_id'=> 'Surah Al-Jinn','ayat'=>'28',],
            ['surat_id'=> 'Surah Al-Muzzammil','ayat'=>'20',],
            ['surat_id'=> 'Surah Al-Muddassir','ayat'=>'56',],
            ['surat_id'=> 'Surah Al-Qiyamah','ayat'=>'40',],
            ['surat_id'=> 'Surah Al-Insan','ayat'=>'31',],
            ['surat_id'=> 'Surah Al-Mursalat','ayat'=>'50',],
            ['surat_id'=> 'Surah An-Naba`','ayat'=>'40',],
            ['surat_id'=> 'Surah An-Nazi`at','ayat'=>'46',],
            ['surat_id'=> 'Surah `Abasa','ayat'=>'42',],
            ['surat_id'=> 'Surah At-Takwir','ayat'=>'29',],
            ['surat_id'=> 'Surah Al-Infitar','ayat'=>'19',],
            ['surat_id'=> 'Surah Al-Tatfif','ayat'=>'36',],
            ['surat_id'=> 'Surah Al-Insyiqaq','ayat'=>'25',],
            ['surat_id'=> 'Surah Al-Buruj','ayat'=>'22',],
            ['surat_id'=> 'Surah At-Tariq','ayat'=>'17',],
            ['surat_id'=> 'Surah Al-A`la','ayat'=>'19',],
            ['surat_id'=> 'Surah Al-Gasyiyah','ayat'=>'26',],
            ['surat_id'=> 'Surah Al-Fajr','ayat'=>'30',],
            ['surat_id'=> 'Surah Al-Balad','ayat'=>'20',],
            ['surat_id'=> 'Surah Asy-Syams','ayat'=>'15',],
            ['surat_id'=> 'Surah Al-Lail','ayat'=>'21',],
            ['surat_id'=> 'Surah Ad-Duha','ayat'=>'11',],
            ['surat_id'=> 'Surah Al-Insyirah','ayat'=>'8',],
            ['surat_id'=> 'Surah At-Tin','ayat'=>'8',],
            ['surat_id'=> 'Surah Al-`Alaq','ayat'=>'19',],
            ['surat_id'=> 'Surah Al-Qadr','ayat'=>'5',],
            ['surat_id'=> 'Surah Al-Bayyinah','ayat'=>'8',],
            ['surat_id'=> 'Surah Az-Zalzalah','ayat'=>'8',],
            ['surat_id'=> 'Surah Al-`Adiyat','ayat'=>'11',],
            ['surat_id'=> 'Surah Al-Qari`ah','ayat'=>'11',],
            ['surat_id'=> 'Surah At-Takasur','ayat'=>'8',],
            ['surat_id'=> 'Surah Al-`Asr','ayat'=>'3',],
            ['surat_id'=> 'Surah Al-Humazah','ayat'=>'9',],
            ['surat_id'=> 'Surah Al-Fil','ayat'=>'5',],
            ['surat_id'=> 'Surah Quraisy','ayat'=>'4',],
            ['surat_id'=> 'Surah Al-Ma`un','ayat'=>'7',],
            ['surat_id'=> 'Surah Al-Kausar','ayat'=>'3',],
            ['surat_id'=> 'Surah Al-Kafirun','ayat'=>'6',],
            ['surat_id'=> 'Surah An-Nasr','ayat'=>'3',],
            ['surat_id'=> 'Surah Al-Lahab','ayat'=>'5',],
            ['surat_id'=> 'Surah Al-Ikhlas','ayat'=>'4',],
            ['surat_id'=> 'Surah Al-Falaq','ayat'=>'5',],
            ['surat_id'=> 'Surah An-Nas','ayat'=>'6',],
           

        ]);
    }
}
